# Generated by Django 4.0 on 2021-12-25 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='stu_college',
            new_name='stu_country',
        ),
    ]
